src/main/java/se/sundsvall/casestatus/integration/opene/OpenEClient.java

only try to find since yesterday

Instead of trying to find every errand from 2021-01-01

---

src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementClient.java
src/main/java/se/sundsvall/casestatus/integration/citizen/CitizenClient.java
src/main/java/se/sundsvall/casestatus/integration/db/CaseManagementOpeneViewRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/CaseTypeRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/CompanyRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/IncidentOpeneViewRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/PrivateRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/UnknownRepository.java
src/main/java/se/sundsvall/casestatus/integration/incident/IncidentClient.java
src/main/java/se/sundsvall/casestatus/integration/opene/OpenEClient.java

UF-11348: Add Circuitbreakers

---

src/main/resources/application.yml

UF-11362: Ignore client problems for casemanagement and incident

---

src/main/java/se/sundsvall/casestatus/api/CaseStatusResource.java
src/main/java/se/sundsvall/casestatus/api/model/CaseStatusResponse.java
src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementClient.java
src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementIntegration.java
src/main/java/se/sundsvall/casestatus/integration/db/PrivateRepository.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/test/java/se/sundsvall/casestatus/api/CaseStatusResourceTests.java
src/test/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementIntegrationTests.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/MapperTest.java

UF-11188: Update CM integration and adjustments to service layer

---

src/integration-test/resources/GetCaseStatusIT/__files/test2_not_found_in_casemanagement_but_match_in_casestatus_db/expected-response.json
src/integration-test/resources/GetOrganisationStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetOrganisationStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_casestatus_db/expected-response.json
src/main/java/se/sundsvall/casestatus/integration/opene/OpenEClient.java
src/main/java/se/sundsvall/casestatus/integration/opene/OpenEIntegration.java
src/main/java/se/sundsvall/casestatus/integration/party/PartyClient.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/main/java/se/sundsvall/casestatus/service/scheduler/CaseStatusCacheWorker.java
src/main/java/se/sundsvall/casestatus/service/scheduler/Mapper.java
src/test/java/se/sundsvall/casestatus/integration/opene/OpenEIntegrationTests.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/MapperTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/CaseStatusCacheWorkerTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/MapperTest.java

UF-11187: Update openE integration to find statuses

---

pom.xml
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/resources/openapi.yaml
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java

UF-11400: Look up cached orgnumbers with or without hyphen

---

src/main/java/se/sundsvall/casestatus/integration/db/model/CaseEntity.java
src/main/java/se/sundsvall/casestatus/integration/db/model/CaseTypeEntity.java
src/main/resources/db/migration/V6_1__add_indexes.sql
src/test/resources/db/schema.sql

UF-11456: Create databaseindexes

---

pom.xml
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/configuration/SupportManagementConfiguration.java
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/configuration/SupportManagementProperties.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/integrations/support-management.yml
src/test/java/se/sundsvall/casestatus/integration/supportmanagement/configuration/SupportManagementConfigurationTest.java
src/test/java/se/sundsvall/casestatus/integration/supportmanagement/configuration/SupportManagementPropertiesTest.java

UF-11541: SupportManagement integration

---

README.md

UF-11160: Update readme

---

src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/mappings/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/mappings/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/responses/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/responses/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/mappings/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/mappings/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/responses/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/responses/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/mappings/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/mappings/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/responses/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/responses/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test4_not_found_anywhere/mappings/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test4_not_found_anywhere/mappings/supportmanagement-namespaces.json
src/integration-test/resources/GetPartyStatusesIT/__files/test4_not_found_anywhere/responses/supportmanagement-getErrands.json
src/integration-test/resources/GetPartyStatusesIT/__files/test4_not_found_anywhere/responses/supportmanagement-namespaces.json
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/MapperTest.java

UF-11545: update servicelayer to use supportManagement integration

---

src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/responses/supportmanagement-getErrands.json
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java

UF-11596: Handle pageable response from supportManagement

---

pom.xml
src/main/java/se/sundsvall/casestatus/integration/eventlog/EventlogClient.java
src/main/java/se/sundsvall/casestatus/integration/eventlog/configuration/EventlogConfiguration.java
src/main/java/se/sundsvall/casestatus/integration/eventlog/configuration/EventlogProperties.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/integrations/eventlog.yml
src/test/java/se/sundsvall/casestatus/integration/eventlog/configuration/EventlogConfigurationTest.java
src/test/java/se/sundsvall/casestatus/integration/eventlog/configuration/EventlogPropertiesTest.java

UF-11638: Add eventlog integration

---

src/main/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCache.java
src/main/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheWorker.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/test/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheScheduledTest.java

UF-11735: Update cachejob to use dept44-scheduler

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogScheduler.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogSchedulerTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-11745: Fixes to eventlog scheduled job

---

src/main/java/se/sundsvall/casestatus/integration/db/model/ExecutionInformationEntity.java
src/main/resources/db/migration/V6_3__drop_familyid_from_execution_table.sql
src/test/java/se/sundsvall/casestatus/integration/db/model/ExecutionInformationEntityTest.java
src/test/resources/db/schema.sql

UF-11745: Correct executionInformation table

---

pom.xml
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-11771: Map SM-status to openE

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-11814: Null handling when filtering out cases to update

---

src/main/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCache.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogScheduler.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml

UF-14254: Set scheduled parameters so they are overrideable

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java

UF-14706: Update filterstring used for eventlog call

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java

Uf-14706: Fix filterstring

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogScheduler.java

UF-14772: Fix time bug in eventlog scheduling

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-14723: Added clock-skew property when fetching events

---

src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java

UF-xxx: Reduce page size towards SM

---

src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/SupportManagementServiceTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-14768: Optimize call towards SM

---

src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/test/java/se/sundsvall/casestatus/service/SupportManagementServiceTest.java

UF-14770: Should only call SALARYANDPENSION namespace

---

src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/SupportManagementServiceTest.java

UF-14855: Should only ask SM for distinict values

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java

UF-14855: Filter distinct logkeys

---

pom.xml
src/integration-test/resources/GetCaseStatusIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetOrganisationStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/expected-response.json
src/main/java/se/sundsvall/casestatus/api/model/CaseStatusResponse.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapper.java
src/main/java/se/sundsvall/casestatus/utility/Constants.java
src/main/resources/openapi.yaml
src/test/java/se/sundsvall/TestDataFactory.java
src/test/java/se/sundsvall/casestatus/api/CaseStatusResourceTests.java
src/test/java/se/sundsvall/casestatus/api/model/CaseStatusResponseTests.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/MapperTest.java
src/test/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapperTest.java

* Updated mapping for CaseManagement, still work in progress unitl changes have been made in CaseManagement. 
* Separated some of the logic to a separate mapper.

UF-15150 CaseManagement mapping

---

src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_opene_and_casestatus_db/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test3_not_found_in_opene_or_casemanagement_but_in_db/expected-response.json
src/main/java/se/sundsvall/casestatus/api/model/CaseStatusResponse.java
src/main/java/se/sundsvall/casestatus/integration/opene/soap/OpenECallbackIntegration.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/Mapper.java
src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/main/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/main/java/se/sundsvall/casestatus/util/Constants.java
src/main/java/se/sundsvall/casestatus/util/FormattingUtil.java
src/test/java/se/sundsvall/TestDataFactory.java
src/test/java/se/sundsvall/casestatus/integration/opene/soap/OpenECallbackIntegrationTest.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/MapperTest.java
src/test/java/se/sundsvall/casestatus/service/SupportManagementServiceTest.java
src/test/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapperTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java
src/test/java/se/sundsvall/casestatus/service/util/FormattingUtilTest.java

* Updated mapping for SupportManagment. 
* Refactored parts of the CaseStatusService for easier readability and testability.

UF-15151 SupportManagement mapping

---

src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

Change to singular requests instead of one big filterstring

---

src/integration-test/resources/GetCaseStatusIT/__files/test2_not_found_in_casemanagement_but_match_in_casestatus_db/expected-response.json
src/integration-test/resources/GetOrganisationStatusesIT/__files/test1_successful/expected-response.json
src/integration-test/resources/GetOrganisationStatusesIT/__files/test2_not_found_in_casemanagement_but_match_in_casestatus_db/expected-response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful_private/response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test2_successful_enterprise/response.json
src/main/java/se/sundsvall/casestatus/integration/db/SupportManagementStatusRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/model/SupportManagementStatusEntity.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/mapper/OpenEMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/main/resources/db/migration/V6_4__add_supportmanagement_status_table.sql
src/test/java/se/sundsvall/TestDataFactory.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTests.java
src/test/java/se/sundsvall/casestatus/service/mapper/OpenEMapperTest.java
src/test/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapperTest.java
src/test/resources/db/schema.sql

* Updated ErrandNumber mapping for Open-E errands. 
* Updated CaseType mapping for supportManagement errands. 
* Added a new entity for supportmanagement statuses and their respective genericStatus, this allows for an easy translation from the underlying status to the generic status we want to display.

UF-15614 CaseStatus adjust search results

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/main/java/se/sundsvall/casestatus/util/Constants.java

UF-16079: Skip rather than throw exception if not e-service channel

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java

UF-16079: pt2: nullcheck

---

src/main/resources/application.yml

UF-16100: ingore 404s from oep-integrator

---

src/main/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheWorker.java
src/main/java/se/sundsvall/casestatus/service/scheduler/cache/domain/FamilyId.java
src/test/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheWorkerTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/cache/domain/FamilyIdTest.java

UF-16159: stop caching errands from families already integreted

---

src/main/java/se/sundsvall/casestatus/integration/casedata/CaseDataIntegration.java

* Change spring filter that fetches errands by property designation to use a like instead of equal predicate

UF-XYZ Spring Filter

---

src/integration-test/resources/GetErrandStatusesIT/__files/test1_getErrandsByErrandNumber/response.json
src/integration-test/resources/GetErrandStatusesIT/__files/test1_getErrandsByErrandNumber/responses/api-casedata-get-errands-namespace1.json
src/integration-test/resources/GetErrandStatusesIT/__files/test1_getErrandsByErrandNumber/responses/api-casedata-get-errands-namespace2.json
src/integration-test/resources/GetErrandStatusesIT/__files/test2_getErrandsByPropertyDesignation/response.json
src/integration-test/resources/GetErrandStatusesIT/__files/test2_getErrandsByPropertyDesignation/responses/api-casedata-get-errands-namespace1.json
src/integration-test/resources/GetErrandStatusesIT/__files/test2_getErrandsByPropertyDesignation/responses/api-casedata-get-errands-namespace2.json
src/main/java/se/sundsvall/casestatus/api/model/CaseStatusResponse.java
src/main/java/se/sundsvall/casestatus/integration/casedata/CaseDataMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/OpenEMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/main/resources/openapi.yaml

* Added property designation to CaseStatusResponse. 
* Updated integration tests to verify correct behaviour.

UF-16218 Extended response

---

src/main/java/se/sundsvall/casestatus/service/scheduler/cache/CaseStatusCacheWorker.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogScheduler.java
src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogSchedulerShedlockTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogSchedulerTest.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-16609: Catch oep-faults and dont break lopp

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/main/resources/application.yml

UF-16622: Extended logging

---

src/main/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorker.java
src/test/java/se/sundsvall/casestatus/service/scheduler/eventlog/EventLogWorkerTest.java

UF-16609: Improve faulthandling and logging

---

pom.xml
src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementIntegration.java
src/main/java/se/sundsvall/casestatus/integration/db/CaseManagementOpeneViewRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/CaseRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/CaseTypeRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/ExecutionInformationRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/SupportManagementStatusRepository.java
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java

UF-16713: Fix log injection vulnerability

---

src/integration-test/resources/GetErrandStatusesIT/__files/test1_getErrandsByErrandNumber/response.json
src/integration-test/resources/GetPartyStatusesIT/__files/test1_successful_private/response.json
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/test/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapperTest.java

UF-16833: map type instead of title

---

pom.xml
src/integration-test/java/openapi/OpenApiSpecificationIT.java
src/main/java/se/sundsvall/casestatus/Application.java
src/main/java/se/sundsvall/casestatus/api/CaseStatusResource.java
src/main/java/se/sundsvall/casestatus/integration/casedata/CaseDataClient.java
src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementClient.java
src/main/java/se/sundsvall/casestatus/integration/casemanagement/CaseManagementIntegration.java
src/main/java/se/sundsvall/casestatus/integration/eventlog/EventlogClient.java
src/main/java/se/sundsvall/casestatus/integration/oepintegrator/OepIntegratorClient.java
src/main/java/se/sundsvall/casestatus/integration/party/PartyClient.java
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementClient.java
src/main/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementIntegration.java
src/main/java/se/sundsvall/casestatus/service/SupportManagementService.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/openapi.yaml
src/test/java/se/sundsvall/casestatus/integration/supportmanagement/SupportManagementIntegrationTest.java
src/test/java/se/sundsvall/casestatus/service/SupportManagementServiceTest.java

UF-17083: Add integration to supportmanagement.getCategories()

---

src/main/resources/application.yml

UF-17170: ingore 404 from casedata

---

src/main/java/se/sundsvall/casestatus/integration/casedata/CaseDataClient.java

dismiss 404

---

src/main/java/se/sundsvall/casestatus/integration/db/StatusesRepository.java
src/main/java/se/sundsvall/casestatus/integration/db/model/StatusesEntity.java
src/main/resources/db/migration/V6_5__add_statuses_table.sql
src/test/java/se/sundsvall/casestatus/integration/db/model/StatusesEntityTest.java
src/test/resources/db/schema.sql

UF-17115: Added StatusesEntity and initial data

---

src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/main/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapper.java
src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTest.java
src/test/java/se/sundsvall/casestatus/service/mapper/CaseManagementMapperTest.java

UF-17232: Changed handling when CM-status or SM-status is null

---

src/main/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapper.java
src/test/java/se/sundsvall/casestatus/service/mapper/SupportManagementMapperTest.java

UF-17332: Changed in mapping of sm-status to externalStatus

---

pom.xml
src/main/java/se/sundsvall/casestatus/service/CaseStatusService.java
src/test/java/se/sundsvall/casestatus/service/CaseStatusServiceTest.java

UF-17335: Throw exception when SM-status is null
